Certificate:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: ${self:custom.apexDomain}
    SubjectAlternativeNames:
        - ${self:custom.draftDomain}
        - ${self:custom.pubDomain}
    DomainValidationOptions:
      - DomainName: ${self:custom.dnsZoneName}
        HostedZoneId: ${self:custom.dnsZoneId}
    Tags:
      - Key: project
        Value: ${self:custom.project}
    ValidationMethod: DNS

# DraftCertificate:
#   Type: AWS::CertificateManager::Certificate
#   Properties:
#     DomainName: ${self:custom.draftDomain }
#     DomainValidationOptions:
#       - DomainName: ${self:custom.draftDomain}
#         HostedZoneId: ${self:custom.dnsZoneId}
#     Tags:
#       - Key: project
#         Value: ${self:custom.project}
#     ValidationMethod: DNS

# PubCertificate:
#   Type: AWS::CertificateManager::Certificate
#   Properties:
#     DomainName: ${self:custom.pubDomain }
#     DomainValidationOptions:
#       - DomainName: ${self:custom.pubDomain}
#         HostedZoneId: ${self:custom.dnsZoneId}
#     Tags:
#       - Key: project
#         Value: ${self:custom.project}
#     ValidationMethod: DNS