Certificate:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: ${self:custom.apexDomain}
    SubjectAlternativeNames:
      - ${self:custom.draftDomain}
      - ${self:custom.pubDomain}
    DomainValidationOptions:
      - DomainName: ${self:custom.apexDomain}
        HostedZoneId: ${self:custom.dnsZoneId}
      - DomainName: ${self:custom.draftDomain}
        HostedZoneId: ${self:custom.dnsZoneId}
      - DomainName: ${self:custom.pubDomain}
        HostedZoneId: ${self:custom.dnsZoneId}
    Tags:
      - Key: project
        Value: ${self:custom.project}
    ValidationMethod: DNS

LiveCertificate:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: ${self:custom.apexDomain}
    SubjectAlternativeNames:
      - ${self:custom.draftDomain}
      # - ${self:custom.wildcardDomain}
      - ${self:custom.pubDomain}
    Tags:
      - Key: project
        Value: ${self:custom.project}
    ValidationMethod: DNS
