StagingCertificate:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: ${self:custom.stagingApexDomain}
    SubjectAlternativeNames:
      - ${self:custom.stagingDraftDomain}
      - ${self:custom.stagingPubDomain}
    DomainValidationOptions:
      - DomainName: ${self:custom.stagingApexDomain}
        HostedZoneId: ${self:custom.dnsZoneId}
      - DomainName: ${self:custom.stagingDraftDomain}
        HostedZoneId: ${self:custom.dnsZoneId}
      - DomainName: ${self:custom.stagingPubDomain}
        HostedZoneId: ${self:custom.dnsZoneId}
    Tags:
      - Key: project
        Value: ${self:custom.project}
    ValidationMethod: DNS

LiveCertificate:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: ${self:custom.livePubDomain}
    SubjectAlternativeNames:
      - ${self:custom.liveDraftDomain}
      - ${self:custom.liveApexDomain}
    Tags:
      - Key: project
        Value: ${self:custom.project}
    ValidationMethod: DNS

LoadBalancerCertificate:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: ${self:custom.pubDomain}
    SubjectAlternativeNames:
      - ${self:custom.draftDomain}
      - ${self:custom.apexDomain}
    Tags:
      - Key: project
        Value: ${self:custom.project}
    ValidationMethod: DNS