DistributionImagesCachePolicy:
  Type: AWS::CloudFront::CachePolicy
  Properties:
    CachePolicyConfig:
      Comment: Image cache policy
      DefaultTTL: 31536000
      MaxTTL: 31536000
      MinTTL: 31536000
      Name: ${self:custom.project}-${sls:stage}-image-policy
      ParametersInCacheKeyAndForwardedToOrigin:
        CookiesConfig:
          CookieBehavior: none
        EnableAcceptEncodingBrotli: true
        EnableAcceptEncodingGzip: true
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Accept
        QueryStringsConfig:
          QueryStringBehavior: all

DistributionAssetsCachePolicy:
  Type: AWS::CloudFront::CachePolicy
  Properties:
    CachePolicyConfig:
      Comment: Assets cache policy
      DefaultTTL: 31536000
      MaxTTL: 31536000
      MinTTL: 31536000
      Name: ${self:custom.project}-${sls:stage}-assets-policy
      ParametersInCacheKeyAndForwardedToOrigin:
        CookiesConfig:
          CookieBehavior: none
        EnableAcceptEncodingBrotli: true
        EnableAcceptEncodingGzip: true
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Accept
        QueryStringsConfig:
          QueryStringBehavior: all

DistributionResponseHeadersPolicy:
  Type: AWS::CloudFront::ResponseHeadersPolicy
  Properties:
    ResponseHeadersPolicyConfig:
      CustomHeadersConfig:
        Items:
          - Header: X-Custom-Header
            Override: false
            Value: RandomValue-1234567890
      Name: CustomHeaders-${sls:stage}

DraftDistribution:
  Type: AWS::CloudFront::Distribution
  Properties:
    Tags:
      - Key: project
        Value: ${self:custom.project}
    DistributionConfig:
      Comment: ${self:custom.project}-${sls:stage}-dist-draft
      Enabled: "true"
      Aliases:
        - ${self:custom.draftDomain}
      ViewerCertificate:
        AcmCertificateArn: ${self:custom.cdnCertificateArn}
        MinimumProtocolVersion: TLSv1.1_2016
        SslSupportMethod: sni-only
      HttpVersion: http2
      DefaultCacheBehavior:
        AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
        TargetOriginId: siteOrigin
        CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # AWS built in disabled cache policy
        OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3 # AWS built in origin request policy
        ViewerProtocolPolicy: redirect-to-https
      CacheBehaviors: ${self:custom.cdnBehaviours}
      Origins:
        - DomainName:
            Fn::GetAtt: [SiteLoadBalancer, DNSName]
          Id: siteOrigin
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
            OriginSSLProtocols:
              - TLSv1
          # OriginCustomHeaders:
          #     - HeaderName: X-Custom-Header
          #       HeaderValue: RandomValue-1234567890

PubDistribution:
  Type: AWS::CloudFront::Distribution
  DependsOn:
    - DistributionImagesCachePolicy
    - DistributionAssetsCachePolicy
  Properties:
    Tags:
      - Key: project
        Value: ${self:custom.project}
    DistributionConfig:
      Comment: ${self:custom.project}-${sls:stage}-dist-pub
      Enabled: "true"
      Aliases:
        - ${self:custom.stagingPubDomain}
        - ${self:custom.stagingApexDomain}
      ViewerCertificate:
        AcmCertificateArn: ${self:custom.cdnCertificateArn}
        MinimumProtocolVersion: TLSv1.1_2016
        SslSupportMethod: sni-only
      HttpVersion: http2
      DefaultCacheBehavior:
        AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
        TargetOriginId: siteOrigin
        CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # AWS built in disabled cache policy
        OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3 # AWS built in origin request policy
        ViewerProtocolPolicy: redirect-to-https
      CacheBehaviors: ${self:custom.cdnBehaviours}
      Origins:
        - DomainName:
            Fn::GetAtt: [SiteLoadBalancer, DNSName]
          Id: siteOrigin
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
            OriginSSLProtocols:
              - TLSv1

DraftDistributionDNS:
  Type: AWS::Route53::RecordSet
  Properties:
    HostedZoneId: ${self:custom.dnsZoneId}
    Name: ${self:custom.draftDomain}
    AliasTarget:
      DNSName: !GetAtt DraftDistribution.DomainName
      HostedZoneId: Z2FDTNDATAQYW2 # This is the hosted zone ID for CloudFront distributions
    Type: A

PubDistributionDNS:
  Type: AWS::Route53::RecordSet
  Properties:
    HostedZoneId: ${self:custom.dnsZoneId}
    Name: ${self:custom.stagingPubDomain}
    AliasTarget:
      DNSName: !GetAtt PubDistribution.DomainName
      HostedZoneId: Z2FDTNDATAQYW2 # This is the hosted zone ID for CloudFront distributions
    Type: A

ApexDistributionDNS:
  Type: AWS::Route53::RecordSet
  Properties:
    HostedZoneId: ${self:custom.dnsZoneId}
    Name: ${self:custom.stagingApexDomain}
    AliasTarget:
      DNSName: !GetAtt PubDistribution.DomainName
      HostedZoneId: Z2FDTNDATAQYW2 # This is the hosted zone ID for CloudFront distributions
    Type: A
