StagingCertificate:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: ${self:custom.apexDomain}
    SubjectAlternativeNames:
      - ${self:custom.draftDomain}
      - ${self:custom.pubDomain}
    DomainValidationOptions:
      - DomainName: ${self:custom.apexDomain}
        HostedZoneId: ${self:custom.dnsZoneId}
      - DomainName: ${self:custom.draftDomain}
        HostedZoneId: ${self:custom.dnsZoneId}
      - DomainName: ${self:custom.pubDomain}
        HostedZoneId: ${self:custom.dnsZoneId}
    Tags:
      - Key: project
        Value: ${self:custom.project}
    ValidationMethod: DNS

# StagingDraftDistributionCertificate:
#   Type: AWS::CertificateManager::Certificate
#   Properties:
#     DomainName: ${self:custom.draftDomain }
#     DomainValidationOptions:
#       - DomainName: ${self:custom.draftDomain}
#         HostedZoneId: ${self:custom.dnsZoneId}
#     Tags:
#       - Key: project
#         Value: ${self:custom.project}
#     ValidationMethod: DNS

# StagingPubDistributionCertificate:
#   Type: AWS::CertificateManager::Certificate
#   Properties:
#     DomainName: ${self:custom.pubDomain }
#     DomainValidationOptions:
#       - DomainName: ${self:custom.pubDomain}
#         HostedZoneId: ${self:custom.dnsZoneId}
#     Tags:
#       - Key: project
#         Value: ${self:custom.project}
#     ValidationMethod: DNS

# LiveDraftDistributionCertificate:
#   Type: AWS::CertificateManager::Certificate
#   Properties:
#     DomainName: ${self:custom.draftDomain }
#     DomainValidationOptions:
#       - DomainName: ${self:custom.draftDomain}
#         HostedZoneId: ${self:custom.dnsZoneId}
#     Tags:
#       - Key: project
#         Value: ${self:custom.project}
#     ValidationMethod: DNS

# LivePubDistributionCertificate:
#   Type: AWS::CertificateManager::Certificate
#   Properties:
#     DomainName: ${self:custom.pubDomain }
#     DomainValidationOptions:
#       - DomainName: ${self:custom.pubDomain}
#         HostedZoneId: ${self:custom.dnsZoneId}
#     Tags:
#       - Key: project
#         Value: ${self:custom.project}
#     ValidationMethod: DNS
